import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
// data
import { getAllPages } from '../lib/api';

export default function Home({ allPages: { edges } }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to our demo blog!</h1>
        <p>
          You can find more articles on the{' '}
          <Link href='/blog'>
            blog
          </Link>
        </p>


        <section>
          {edges.map(({ node }) => (
            <div key={node.id}>
        {/*       <div className={blogStyles.listitem__thumbnail}>
                <figure>
                  <img
                    src={node.extraPostInfo.thumbImage.mediaItemUrl}
                    alt={node.title}
                  />
                </figure>
              </div> */}
              <div>
                <h2>{node.title}</h2>
        {/*         <p>{node.extraPostInfo.authorExcerpt}</p> */}
                <Link href={`/${node.slug}`}>
                   {node.title}
                </Link>
              </div>
            </div>
          ))}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const allPages = await getAllPages();
  return {
    props: {
      allPages
    }
  };
}